//Call any scripts for item activation here
void main()
{
	// Auto-Generated by Legends Master Configurator 1.92
	ExecuteScript("leg_all_mastermod_itemactivated", OBJECT_SELF);
	
    object oItem = GetItemActivated();
 	if(GetLocalInt(oItem, "healAmt") > 0)
	{
		ExecuteScript("foodHeal", oItem);
	}
	else
	{ 
		ExecuteScript("itemconvo", oItem);
	}
}