void main()
{
	object oBY = GetModuleItemAcquiredBy();
	if (GetResRef(oBY) == "sfpb_storage") return;
	// Auto-Generated by Legends Master Configurator 1.93
	ExecuteScript("leg_all_mastermod_itemacquired", OBJECT_SELF);
}