// Script to handle item activations!
void main()
{
	// Auto-Generated by Legends Master Configurator 1.92
	ExecuteScript("leg_all_mastermod_itemactivated", OBJECT_SELF);
	
	// Get the PC!
	object oPC = GetItemActivator();
	
	// Tell the PC to start a conversation with himself!
	AssignCommand(oPC, ActionStartConversation(oPC, "tinderbox"));
}