// =============================================================
//
//    File: row_rbs_brw_1000
//    Desc: Rowell's Banking System - Borrow on Loan 1000gp
//  Author: Michael Marzilli
//    Site: http://www.engliton.org
//
// Created: Nov 15, 2006
// Updated: Nov 15, 2006
// Version: 1.0.0
//
// =============================================================

#include "row_inc_banking"


void main() {

	RBS_Borrow(1000);
	
}