// =============================================================
//
//    File: row_rbs_dep_50
//    Desc: Rowell's Banking System - Deposit 50gp
//  Author: Michael Marzilli
//    Site: http://www.engliton.org
//
// Created: Nov 15, 2006
// Updated: Nov 15, 2006
// Version: 1.0.0
//
// =============================================================

#include "row_inc_banking"


void main() {

	RBS_Deposit(50);
	
}
