// =============================================================
//
//    File: row_rbs_wth_10000
//    Desc: Rowell's Banking System - Withdraw 10000gp
//  Author: Michael Marzilli
//    Site: http://www.engliton.org
//
// Created: Nov 15, 2006
// Updated: Nov 15, 2006
// Version: 1.0.0
//
// =============================================================

#include "row_inc_banking"


void main() {

	RBS_Withdraw(10000);
	
}